# services:
#     nginx:
#         image: nginx:latest
#         container_name: nginx
#         ports:
#             - "80:80"
#         restart: always

FROM nginx:latest
COPY index.html /usr/share/nginx/html/index.html
EXPOSE 80